export const ADMIRE_SUCCESS = 'TOPIC_LIST/ADMIRE_SUCCESS'
export const GET_TOPIC_INFO = 'TOPIC_LIST/GET_TOPIC_INFO'
export const GET_TOPIC_LIST = 'TOPIC_LIST/GET_TOPIC_LIST'
export const APPEND_TOPIC_LIST = 'TOPIC_LIST/APPEND_TOPIC_LIST'
